### ISSUE TITLE
Suggest freegroup to Imports rather than Suggests

### ISSUE THREAD

**Issue by chris-english** [stla/PlaneGeometry#1]
R CMD build PlaneGeometry
* creating vignettes ... ERROR
--- re-building ‘examples.Rmd’ using rmarkdown
The infinite line meets the circle at two points, but one of them is not on the half-line.
M is on the line
Quitting from lines 786-856 (examples.Rmd) 
Error: processing vignette 'examples.Rmd' failed with diagnostics:
there is no package called 'freegroup'
--- failed re-building ‘examples.Rmd’

I check that I have all Imports. Suggests are maybe checked. In this case I had nearly all, but valuable information from vignettes (and ability to build) depend on `freegroup`, so this might be elevated. 
Respectfully submitted.

**Comment by stla** [comment]
R CMD CHECK would throw an error or a warning if I put `freegroup` in **Imports**, because the package does not use `freegroup`.
